Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-20.04"


   config.vm.network "private_network", ip: "192.168.33.20"

  # config.vm.provision "shell", inline: <<-SHELL
   #  apt-get update
    # apt-get install -y nginx
	 #cp /vagrant/index.html /var/www/html
	 #cp /vagrant/unknown.jpg /var/www/html/index.html

   #SHELL
end
