version: '2' 

volumes:
  vol_nginx: 
 
networks:
  net_nginx: 

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
     - vol_nginx:/var/www
    environment:
      - VARIABLE=truc
    ports:
      - "80:80" 
    networks: 
      - net_nginx