Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.define "docker" do |docker|
    docker.vm.hostname = "mydocker"
    docker.vm.network "private_network", ip: "192.168.33.10"
	docker.vm.provision "ansible_local" do |ansible|
		ansible.become = true
		ansible.playbook = "docker/playbook.yml"
		ansible.galaxy_role_file = "docker/requirements.yml"
		ansible.galaxy_roles_path = "/etc/ansible/roles"
		ansible.galaxy_command = "sudo ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path} --force"
	end
  end
end
